apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db   # MongoDB’s default data directory
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc   # must match your PVC name              
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb  # name is optional but when creating multiple port creating you want to give name, can be anything
  ports:
    - name: mongodb  # name is optional, can be anything
    - protocol: TCP
      port: 27017
      targetPort: 27017
